### ISSUE TITLE
Feature: Real-Time Ray tracing 

### ISSUE THREAD

**Issue by bipul-mohanto** [electronicarts/gigi#1]
Hi! Thanks for such a wonderful public codebase. Is there any plan to add a real-time ray-tracing feature?

**Comment by Atrix256** [comment]
Good news, raytracing is supported :)
Some examples:

Techniques\ShaderToy\DemofoxNeonDesert.gg is a stylized path tracer
![image](https://github.com/user-attachments/assets/6688d64a-6dca-4390-9cbc-cb626c2a23c4)

Techniques/UnitTests/RayTrace has several .gg file examples that show how to do ray gen shaders, custom intersection shaders, and inline raytracing.

Anyhit.gg
![image](https://github.com/user-attachments/assets/ad2a5469-e61c-4d86-ac57-d9272835020b)

IntersectionShader.gg
![image](https://github.com/user-attachments/assets/930def68-8988-4345-b009-adb8582ee076)

You can also do stuff like ray traced ambient occlusion, but this example is not public because we don't have permission to share the model used in the render.  This is an image from a research paper we published on sampling in raytracing using a new type of noise texture.
![image](https://github.com/user-attachments/assets/3c7b9f04-0e6c-4594-b42e-52e792ea8dc2)

We need to make more tutorials, or better documentation for how to do things in Gigi, but for now I'd say check out the examples in Techniques/UnitTests/RayTrace to see how to do raytracing.

One caveat though is that you can't yet use dynamic vertex buffers for raytracing.  What i mean is that you can give it a .obj file to raytrace, but you can't raytrace the output of a compute shader. That isn't working yet.

**Comment by bipul-mohanto** [comment]
Hi @Atrix256, thanks for your details reply. So, both real-time ray and path tracing are included in the framework. From my understanding, this framework could be equivalent to NVidia's [Falcor](https://developer.nvidia.com/falcor), but instead of rendering, gigi is more focused on the research idea for game development, right? Although I know it is irrelevant, but good to know, do you have any future plans to extend it to XR applications?

**Comment by Atrix256** [comment]
Great questions!
Gigi and Falcor both aim to give you an easier way to do graphics programming.  I was actually at NVIDIA before EA and used / made code contributions to Falcor.
Gigi is more fully featured than Falcor though, and doesn't require C++ programming - it's just nodes in a node graph, and shader files.
Falcor is a bit like a light weight game dev rendering engine, while Gigi is written more like a more powerful version of shadertoy.
Gigi also lets you generate code when you are done, if you want to use what you made elsewhere.
As far as XR, there aren't plans to make the viewer support XR, but since XR can use DX12, and this can code generate DX12, that's a way you could use what you made in XR.  In the future when Gigi has more code generation targets, those will be other avenues to XR.
To say that more explicitly - if you made a denoiser in Gigi, you could generate code for that denoiser, and then use that in XR.

**Comment by bipul-mohanto** [comment]
Thanks, @Atrix256, I am already very familiar with your amazing work. Moreover, your explanation really helps.
